/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductDetails = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Null,
  'coinbaseICP' : IDL.Null,
});
export const OrderId = IDL.Text;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const OrderDetails = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'productIds' : IDL.Vec(ProductId),
  'userId' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quantities' : IDL.Vec(IDL.Nat),
});
export const DonationRequest = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'message' : IDL.Text,
  'currency' : IDL.Text,
  'amount' : IDL.Nat,
});
export const DonationRecord = IDL.Record({
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'message' : IDL.Text,
  'currency' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'donor' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ShoppingCart = IDL.Record({
  'id' : IDL.Text,
  'productIds' : IDL.Vec(ProductId),
  'userId' : IDL.Principal,
  'quantities' : IDL.Vec(IDL.Nat),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PaymentResult = IDL.Record({
  'orderId' : IDL.Opt(OrderId),
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductDetails], [ProductDetails], []),
  'addToCart' : IDL.Func([IDL.Text, ProductId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, PaymentMethod],
      [IDL.Opt(OrderDetails)],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'donate' : IDL.Func([DonationRequest], [DonationRecord], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([IDL.Text], [IDL.Opt(ShoppingCart)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductDetails)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductDetails)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processCoinbasePayment' : IDL.Func([OrderId], [PaymentResult], []),
  'removeFromCart' : IDL.Func([IDL.Text, ProductId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'storeFile' : IDL.Func([ExternalBlob], [], []),
  'storeImage' : IDL.Func([ExternalBlob], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProduct' : IDL.Func([ProductDetails], [ProductDetails], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductDetails = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Null,
    'coinbaseICP' : IDL.Null,
  });
  const OrderId = IDL.Text;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const OrderDetails = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'productIds' : IDL.Vec(ProductId),
    'userId' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quantities' : IDL.Vec(IDL.Nat),
  });
  const DonationRequest = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'message' : IDL.Text,
    'currency' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const DonationRecord = IDL.Record({
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'message' : IDL.Text,
    'currency' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ShoppingCart = IDL.Record({
    'id' : IDL.Text,
    'productIds' : IDL.Vec(ProductId),
    'userId' : IDL.Principal,
    'quantities' : IDL.Vec(IDL.Nat),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PaymentResult = IDL.Record({
    'orderId' : IDL.Opt(OrderId),
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductDetails], [ProductDetails], []),
    'addToCart' : IDL.Func([IDL.Text, ProductId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, PaymentMethod],
        [IDL.Opt(OrderDetails)],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'donate' : IDL.Func([DonationRequest], [DonationRecord], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([IDL.Text], [IDL.Opt(ShoppingCart)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(OrderDetails)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(ProductDetails)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductDetails)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processCoinbasePayment' : IDL.Func([OrderId], [PaymentResult], []),
    'removeFromCart' : IDL.Func([IDL.Text, ProductId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'storeFile' : IDL.Func([ExternalBlob], [], []),
    'storeImage' : IDL.Func([ExternalBlob], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProduct' : IDL.Func([ProductDetails], [ProductDetails], []),
  });
};

export const init = ({ IDL }) => { return []; };