/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DonationRecord {
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'message' : string,
  'currency' : string,
  'timestamp' : bigint,
  'amount' : bigint,
  'donor' : Principal,
}
export interface DonationRequest {
  'paymentMethod' : PaymentMethod,
  'message' : string,
  'currency' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface OrderDetails {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'productIds' : Array<ProductId>,
  'userId' : Principal,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'quantities' : Array<bigint>,
}
export type OrderId = string;
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'completed' : null };
export type PaymentMethod = { 'stripe' : null } |
  { 'coinbaseICP' : null };
export interface PaymentResult {
  'orderId' : [] | [OrderId],
  'message' : string,
  'success' : boolean,
}
export interface ProductDetails {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type ProductId = string;
export interface ShoppingCart {
  'id' : string,
  'productIds' : Array<ProductId>,
  'userId' : Principal,
  'quantities' : Array<bigint>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductDetails], ProductDetails>,
  'addToCart' : ActorMethod<[string, ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[string, PaymentMethod], [] | [OrderDetails]>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'donate' : ActorMethod<[DonationRequest], DonationRecord>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[string], [] | [ShoppingCart]>,
  'getOrders' : ActorMethod<[], Array<OrderDetails>>,
  'getProduct' : ActorMethod<[ProductId], [] | [ProductDetails]>,
  'getProducts' : ActorMethod<[], Array<ProductDetails>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processCoinbasePayment' : ActorMethod<[OrderId], PaymentResult>,
  'removeFromCart' : ActorMethod<[string, ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storeFile' : ActorMethod<[ExternalBlob], undefined>,
  'storeImage' : ActorMethod<[ExternalBlob], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProduct' : ActorMethod<[ProductDetails], ProductDetails>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];